# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9131b95af2da62046bee842204e48aaac1ec4b3c4818a26af7007adad6206ee7b948f6e070b72773f1baf8fe1a659024ef585a3b5b1148ee831151b4900dabc6

test:
  secret_key_base: fed769053078e77dd27ee9f0b6ca7de020ed8e0ea26be2c610767368db4822a9c52999f94c23d9616d16cdaf36b388c7d6b76726ad616dfb3ef51a37d80b0f87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
